### ISSUE TITLE
На десктопе обложка отображается как фон.

### ISSUE THREAD

**Issue by Kiliar** [grin3671/shiki-theme#44]
На фоне стоит обложка вместо фона, в то время как сам фон пропал. Последняя версия стилей из сборщика. https://shikimori.one/Kiliar

Вот значения переменных:

`  /* Обложка профиля */
  --user-cover: url(https://i.imgur.com/OI5qCkB.jpg);
  /* Фон сайта */
  --user-background: url(https://i.imgur.com/V5jEbLk.png);`

![image](https://user-images.githubusercontent.com/6061686/115060612-bfac1e80-9ef0-11eb-8ce5-0b57fcf81d7a.png)
![image](https://user-images.githubusercontent.com/6061686/115060674-d3578500-9ef0-11eb-8bad-1dcf99cf48d9.png)

**Comment by grin3671** [comment]
Название «Полноэкранная _обложка_» подсказывает, что так и задумано. Можно перезаписать правило:
```css
@media (min-width: 960px) {
  body {
    --user-cover: var(--user-background);
  }
}
```
