### ISSUE TITLE
"Мой список" отображается на странице другого пользователя

### ISSUE THREAD

**Issue by lijspoop** [grin3671/shiki-theme#52]
https://github.com/grin3671/shiki-theme/blob/8c8ef05dc998bebad0d714789259d38a1c66ab01/assets/blocks/b-collection-filters.sass#L118-L124
![image](https://github.com/user-attachments/assets/def34939-5ce7-4a30-a896-5176f6e76b21)

Я думаю лучше убрать эту замену, либо найти что-нибудь определяющее, что этот список именно мой.

Я смог решить это таким способом:
```css
.b-collection-filters .mylist-block .subheadline::after {
	content: 'Список';
}
.l-top_menu-v2:has(.menu-dropdown > .icon-anime_list) + .l-page .b-collection-filters .mylist-block .subheadline::after {
	content: 'Мой список';
}
```
